export const FETCH_DATA="FETCH_DATA";
export const FETCH_DATA_SUCCESS="FETCH_DATA_SUCESS";
export const FETCH_DATA_ERROR="FETCH_DATA_ERROR";
export const FETCH_DATA_SAGA="FETCH_DATA";
export const FETCH_DATA_SAGA_SUCCESS="FETCH_DATA_SUCESS";